### ISSUE TITLE
DCP corrected records was not incorporated

### ISSUE THREAD

**Issue by AmandaEyer** [NYCPlanning/db-housing#11]
Perhaps partially but not entirely? I just checked for assisted living institutions and those are not incorporated.

**Comment by AmandaDoyle** [comment]
@AmandaEyer should the dcp_occ_pr value in the housing_input_dcpattributes overwrite the dcp_occ_category field?  Or the occ_prop field?  Or...?

**Comment by AmandaDoyle** [comment]
@AmandaEyer Can you review https://github.com/NYCPlanning/db-housing/blob/master/housing_build/sql/dcpdataattributes.sql to make sure that fields are mapped correctly from the DCP attributes table to the fields their supposed to overwrite?
