### ISSUE TITLE
Job 104592068 has a dob_occ_init and prop with a period, and is not classified

### ISSUE THREAD

**Issue by AmandaEyer** [NYCPlanning/db-housing#13]

**Comment by AmandaDoyle** [comment]
Added `UPDATE housing
SET dob_occ_prop = split_part(dob_occ_prop, '.', 2)
WHERE dob_occ_prop LIKE '.%';` to clean.sql to remove the leading period and make the occupancy code and have it match the lookup value in housing_input_lookup_occupancy.csv
