### ISSUE TITLE
thousands of records are missing

### ISSUE THREAD

**Issue by AmandaEyer** [NYCPlanning/db-housing#14]
Not sure what happened. For example, about 6000 NB records are missing compared to the previous version. Maybe this has to do with the occupancy codes? I  don't know.

**Comment by AmandaDoyle** [comment]
For a job number from dob_jobapplications to be inserted into the housing database it must meet the following parameters:
`WHERE jobdocnumber = '01' AND (jobtype = 'A1' OR jobtype = 'DM' OR jobtype = 'NB') AND (proposedoccupancy LIKE '%R%' OR existingoccupancy LIKE '%R%');`
code is here
https://github.com/NYCPlanning/db-housing/blob/master/housing_build/sql/jobnumber.sql

none of the job numbers in the the "missing" list meet these parameters
Please open a new issue if you'd like to change the parameters
