### ISSUE TITLE
the database is missing a status_x_year field

### ISSUE THREAD

**Issue by AmandaEyer** [NYCPlanning/db-housing#16]
Status A through X contain dates but not years. I think year fields are the basis for 90% of the analyses, so it would be practical to have those.

**Comment by AmandaDoyle** [comment]
@AmandaEyer can you calculate the year from the date?  Or would you really like an status_XYZ_year field for each of the statuses?

**Comment by AmandaEyer** [comment]
I think if there isn't a year field, Bill and many others will end up creating it, and so it will save a bunch of people the hassle. So, yes please, for now it would be great to have year field, but just for status_a and status_q

**Comment by AmandaEyer** [comment]
The first. 1. It's one field taking the year value from status_x: but only for **status_a and status_q**

**Comment by AmandaDoyle** [comment]
2 fields. One status_a_year and the other status_q_year

**Comment by AmandaDoyle** [comment]
Added statusyear.sql
