### ISSUE TITLE
Missing records because parameters does not include pre-2008 residential code (J-0, J-2, J-3)

### ISSUE THREAD

**Issue by AmandaEyer** [NYCPlanning/db-housing#17]
The thousands of missing records are due to dob_jobapplications containing old occupancy codes for residential under proposedoccupancy and existingoccupancy, and those not being picked up when selecting LIKE '%R%'. 

The occupancy code lookup table contains the pre2008 residential codes.

Does this mean the occupancy code lookup table is not functioning properly?

**Comment by AmandaDoyle** [comment]
@AmandaEyer So does this mean that the logic should be - add the record if the occupancy code is in the occupancy code lookup table AND its NB, DM, OR A1 AND it's DocNumber 1?

**Comment by AmandaDoyle** [comment]
@AmandaEyer OR does this mean that the query should just include R and J occupancy codes?

**Comment by AmandaDoyle** [comment]
Decide we include R and J occupancy codes.  Waiting to hear back re decision about including R-1 or J-1 (hotel / dormitory) occupancy code

**Comment by AmandaDoyle** [comment]
Decided to revise database an include all occupancy codes and split out 2 exports, one with R and J codes, the second with all occupancy codes.
