### ISSUE TITLE
Please pull "Job Description" field from Job Applications file

### ISSUE THREAD

**Issue by AmandaEyer** [NYCPlanning/db-housing#18]
Include job_description field from the Job Applications file in the database (this is a new field, does not currently exist in database)

**Comment by AmandaDoyle** [comment]
added `job_description` field to create.sql and am inserting the `jobdescription` value from `dob_jobapplications` into the housing table in jobnumber.sql

**Comment by AmandaEyer** [comment]
This hasn't seemed to work?

**Comment by AmandaEyer** [comment]
This field is still missing in current output
