### ISSUE TITLE
Add "mixed_use_flag" field to database

### ISSUE THREAD

**Issue by AmandaEyer** [NYCPlanning/db-housing#19]
the job description field can help determine whether a building is mixed use or not.  Please add an additional field to the database, which is filled based on content in job_description field. This would be a binary field, meaning that a record is flagged for possibly being mixed use. (don't care what the field is called. "mixed_use_flag" is just a suggestion.)

Please flag: 
Records where job_description LIKE '%MIX%'; or
Records where job_description contains both '%RES%' AND '%COMM%'; or
Records where job_description contains both '%RES%' AND '%HOTEL%'; or
Records where job_description contains both '%RES%' AND '%RETAIL%'; or

**Comment by AmandaDoyle** [comment]
Added `x_mixeduse` field in create.sql and created mixeduseflag.sql to populate `x_mixeduse` with true value if it meets the parameters specified above

**Comment by AmandaEyer** [comment]
This also hasn't seemed to work?
