### ISSUE TITLE
Recoding of Garages and Rear Building  Records

### ISSUE THREAD

**Issue by BillS85** [NYCPlanning/db-housing#23]
Amanda,
I noticed that house number field sometimes includes the phrase GAR or REAR to indicate  a secondary building on a lot. It would be helpful  if we could remove these records from a Residential  classification and reclassify as Garage/Storage. This would include NB's and Demolition applications.

**Comment by AmandaEyer** [comment]
[GarageFlag.xlsx](https://github.com/NYCPlanning/db-housing/files/2353996/GarageFlag.xlsx)

These are the records that should be reclassified as DCP occupancy "Garage/Miscellaneous"

**Comment by AmandaEyer** [comment]
Where job_type is Demolition or Alteration 
AND address contains REAR or where address contains GAR%  EXCEPT garibaldi, garretson, garretsons, garland, garrison, garden, garnet, garret, garfield, garvey, garson, gary (no percentage sign before GAR - so that words like Margaret or Edgar don't get selected)

reclassify
**occ_init: Garage/Miscellaneous
occ_prop: Garage/Miscellaneous**


421536939
421519039
421519663
421519672
421518708
421519020
421536314
421536323

**Comment by AmandaDoyle** [comment]
@AmandaEyer 
`SELECT COUNT(*)
FROM housing
WHERE (dob_type = 'DM' OR dob_type = 'A1')
AND (upper(address) LIKE 'GAR%')`
yields no results.  

`SELECT COUNT(*)
FROM housing
WHERE (dob_type = 'DM' OR dob_type = 'A1')
AND upper(address) LIKE '%REAR%';` yields 379 results

What am I missing in this logic?

**Comment by AmandaDoyle** [comment]
@AmandaEyer for the 8 job numbers listed I would add them to housing_input_dcpattributes.csv by adding the columns occ_init and occ_prop, adding a row with each of these job numbers, and then setting the value in occ_init and occ_prop to Garage/Miscellaneous

**Comment by AmandaDoyle** [comment]
Implemented garage.sql 
`UPDATE housing
SET occ_init = 'Garage/Miscellaneous' AND occ_prop = 'Garage/Miscellaneous'
WHERE (dob_type = 'DM' OR dob_type = 'A1')
AND (upper(job_description) LIKE '%GARAGE%' OR upper(address) LIKE '%REAR%');`

@AmandaEyer needs to add 8 job numbers to housing_input_dcpattributes.csv

**Comment by AmandaEyer** [comment]
Great, so I checked qc_garage and it works well with the current criteria:

`WHERE (dob_type = 'DM' OR dob_type = 'A1')AND (upper(job_description) LIKE '%GARAGE%' OR upper(address) LIKE '%REAR%');`

One update I do have: exclude from the selection A1 jobs where the job description contains garage and u_net is NOT 0 or blank. 

Is this possible?

**Comment by AmandaDoyle** [comment]
Can do
Updated the query in garage.sql to the following
`UPDATE housing
SET occ_init = 'Garage/Miscellaneous' AND occ_prop = 'Garage/Miscellaneous'
WHERE (dob_type = 'DM' 
	AND (upper(job_description) LIKE '%GARAGE%' OR upper(address) LIKE '%REAR%'))
OR (dob_type = 'A1'
	AND (upper(job_description) LIKE '%GARAGE%' OR upper(address) LIKE '%REAR%') 
	AND (units_net::numeric = 0 OR units_net::numeric IS NULL));`
