### ISSUE TITLE
Update to mixed use flag

### ISSUE THREAD

**Issue by AmandaEyer** [NYCPlanning/db-housing#25]
Please update paremeters for mixeduseflag.sql to populate x_mixeduse as follows:

 Records where job_description LIKE '%MIX%'; or
 Records where job_description contains both '%RESID%' AND '%COMM%'; or
 Records where job_description contains both '%RESID%' AND '%HOTEL%'; or
 Records where job_description contains both '%RESID%' AND '%RETAIL%';

**Comment by AmandaDoyle** [comment]
Done - changed RES to RESID

**Comment by AmandaEyer** [comment]
This field is missing in the current output, as well as the job description field.
