### ISSUE TITLE
Negative 2018 Unit change Numbers

### ISSUE THREAD

**Issue by BillS85** [NYCPlanning/db-housing#31]
Negative 2018 unit change counts totaled -9,955. Something is amiss here.
Also Checked the residential units issued permit in 2018 to the end of July and it differs by 300 units from the tally I keep on a monthly basis. So that is good.

**Comment by AmandaDoyle** [comment]
unit_change_2018 is u_2018_existtota - u_2017_existtotal (cofoincrem.sql) 

When I do SELECT SUM(unit_change_2018::numeric) FROM housing; I get 10309 units

Also note that only 1/2 of 2018 is reported, (Jan to June) so a full year of units is not accounted for

**Comment by BillS85** [comment]
Will Look at it tomorrow. Thanks!

**Comment by AmandaDoyle** [comment]
And if I do Select sum for just the housing table that I shared then i get +7233 units
The housing table that I shared has 145,357 records

**Comment by AmandaEyer** [comment]
Bill is correct, there is an issue with the 2018 unit change numbers. I assume the problem is the underlying data, but we have to change the code in order to reflect this... 
See attached a screenshot of the problem. So units that received COs in 2017 suddenly show up negative for 2018... it must be some wonky DOB thing???
![capture](https://user-images.githubusercontent.com/39066142/45716528-a9962000-bb86-11e8-8f65-420bc55f370b.JPG)

**Comment by AmandaDoyle** [comment]
This illustrates the need to refactor the database.
The code is unwieldy.  Each time a new year is added there are numerous places where the code needs to be updated, making it easy to miss a place needing an update and causing this error.

I updated cofosfillexisting so the math for 2018 is correct now; however this still results in some records having a negative unit change count (ie 121324717) but this is correct 
u_2016_existtotal       | 476
u_2017_existtotal       | 792
u_2018_existtotal       | 616

unit_change_2016        | 476
unit_change_2017        | 316
unit_change_2018        | -176

The unit count is indeed negative

**Comment by AmandaEyer** [comment]
Thanks, sounds good. Yes, some records do have remaining negative unit counts (I think this is almost exclusively the case when u_net exceeds u_prop.). Not ideal, still. I think there should now be language in qc_outliers to capture those records, so that we can decide what to do with them.

**Comment by AmandaDoyle** [comment]
Improved qc_outliers.sql by adding a flag field indicating why that record was added to the outliers file AND
added another group pulling out records if the value in the latest unit_change count field is negative
