### ISSUE TITLE
Assisted Liviving with Other DCP category

### ISSUE THREAD

**Issue by BillS85** [NYCPlanning/db-housing#32]
I noticed 23 records that have occ_prop as "Assisted Living Institution" but have a dcp_occ_category defined as "Other". Job Number  320123914 is described in BIS Schedule A as :
THIS IS A FOUR STORY ASSISTED LIVING FACILITY WITH 174 DWELLING UNITS.
 Maybe a reclassification of the following job numbers:
421360609
321569655
210080213
310195204
220051119
121188614
110374951
220603504
220542955
320916844
220539022
121327475
520328422
320206040
320123914
121555370
320051689
220111484
420067180
320175831
220010173
220107024
420207760

**Comment by AmandaDoyle** [comment]
Updated dcpoccupancy.sql to label records where occ_init LIKE '%Assisted%Living%' OR occ_prop LIKE '%Assisted%Living%' as Residential
