### ISSUE TITLE
HDB looking Good But.....

### ISSUE THREAD

**Issue by BillS85** [NYCPlanning/db-housing#33]
Hello Amanada,
Looking over the August HDB and noticed that the status_q_year field is giving the month-date instead of the year and that the negative unit count numbers in the unit_change2018 field is way out of proportion when you compare it to the number of records for previous years that contain negative numbers. Other that these two items it looks good.

Bill

**Comment by AmandaEyer** [comment]
Yes, the Status_q_year field needs to be properly formatted - the data is currently not showing as a year.

**Comment by AmandaDoyle** [comment]
Updated statusyear.sql so that it is getting the first 4 characters.  status_q is formatted differently than other date fields
