### ISSUE TITLE
Change code for outliers QC

### ISSUE THREAD

**Issue by AmandaEyer** [NYCPlanning/db-housing#34]
Remove two criteria from current code and add other criteria:

CURRENT CODE:
-- Generate list of potential outliers for removal 
2  -- criteria 
3  -- 1) top 20 and bottom 20 for units_net (REMOVE)
4  -- 2) top 20 for units_init and top 20 for units_prop  (REMOVE)
5  -- 3) units_net_complete is 50+ units greater than units proposed (NBs only)  **(KEEP)**

Add other criteria:

4) job_type= DM and units_init > 19
5) job_type= A1 and units_net < -50
6 )  job_type= A1, TOP 20 for units_net
7)  job_type= A1, TOP 10 for u_prop
8) job_type= NB and units_init NOT 0
9) job_description (_field does not currently exist_) contains both '%RESID%' AND '%HOTEL%'

Also, these job numbers are outliers (I can commit myself if easy):
120700795
121712405
104350532
220014400
122835593

**Comment by AmandaDoyle** [comment]
Updated code to generate qc_outliers based on requirements above.  Regenerated qc_outliers.csv.  5 job numbers listed are in new output
