### ISSUE TITLE
Criteria for Final Outputs (both housing and all developments)

### ISSUE THREAD

**Issue by AmandaEyer** [NYCPlanning/db-housing#35]
In final output, please only include records where either: 

CO date is Jan 1 2010 through June 30 2018, or
if no CO date exist, status_q date is Jan 1 2010 through June 30 2018, or
if no status_q exist, status_a_year date should be is Jan 1 2010 through June 30 2018

If we have a developments database that is updated on a quarterly basis, this would be the cutoff date for the 2nd quarter. 

Cutoff date for 1st quarter would be March 31st.
Cutoff date for 3rd quarter is Sept 30th.
Cutoff date for 4th quarter is Dec 31st.

**Comment by AmandaDoyle** [comment]
Added the following where clause to export.sql so that only records in the specified range are exported
`	WHERE (earliest_effectivedate::date >= '2010-01-01' AND earliest_effectivedate::date <=  '2018-06-30')
	OR (earliest_effectivedate IS NULL AND status_q::date >= '2010-01-01' AND status_q::date <=  '2018-06-30')
	OR (earliest_effectivedate IS NULL AND status_q IS NULL AND status_a::date >= '2010-01-01' AND status_a::date <=  '2018-06-30')`
