### ISSUE TITLE
Issue with unit_change field for 2010 and 2011

### ISSUE THREAD

**Issue by AmandaEyer** [NYCPlanning/db-housing#36]
the unit change fields for 2010 are not computed (pre and post April). Certain values seem to have been kicked into the 2011 unit change field? 

A sum of NB applications for unit_change 2011 should add up to about 16,000 units and the 2010 total should be about 23,000.

**Comment by AmandaDoyle** [comment]
Miscalled a variable in cofos.sql so u_2010pre_existtotal and u_2010post_existtotal were not being assigned any numofdwellingunits.  Corrected the issue
In current cut of data
SELECT SUM(unit_change_2011::numeric) FROM housing WHERE dob_type = 'NB'; returns 18315 
And
SELECT SUM(unit_change_postapr2010::numeric) FROM housing WHERE dob_type = 'NB'; returns 18704
And 
SELECT SUM(unit_change_preapr2010::numeric) FROM housing WHERE dob_type = 'NB'; returns 5839
