### ISSUE TITLE
Small other things to discuss

### ISSUE THREAD

**Issue by AmandaEyer** [NYCPlanning/db-housing#37]
- [ ] - I am confused by the DCP_occ_cat field. what purpose does it serve? Why do the records that are classified as "other" say "assisted living institution" in the occ_prop?

- [x] does the DUP flag still have a purpose?

- [ ] - what about units hotel / residential in DCP lookup table?

- [x] Ifor these jobnumbers, **occ_init** should be changed to the following:
520238252 = Medical and other custodial institutions
320988393 = Medical and other custodial institutions
122788288 = Hotel or Dormitory
321390632 = Industrial, Storage & Utilities
123178578 = Assisted Living Institution
122822785 = Assisted Living Institution
123013817 = Assisted Living Institution
122979009 = Assisted Living Institution
123190484 = Assisted Living Institution
123201971 = Assisted Living Institution

**Comment by AmandaDoyle** [comment]
@AmandaEyer let me know when you want to discuss these items so that I can address them and close the issue

**Comment by AmandaDoyle** [comment]
issues have been discussed and addressed - closing
