### ISSUE TITLE
Complete unit_change field for Demolitions

### ISSUE THREAD

**Issue by AmandaEyer** [NYCPlanning/db-housing#38]
where job_type= Demolition

add values to the unit_change field. these will be negative, and based on the year of issuance of status q Permit.

so, for example: if status q is reached in 2012 and 1 unit is demolished, add -1 to unit_change_2012 field

**Comment by AmandaDoyle** [comment]
@AmandaEyer is this needed by population for their projections?

**Comment by AmandaDoyle** [comment]
@EricaMaurer looping you in too

**Comment by EricaMaurer** [comment]
@AmandaDoyle yes, we will need demolitions included in the housing counts for the projections

**Comment by AmandaDoyle** [comment]
Added logic to cofosincrem.sql
so that for dob_type = 'DM' the unit change field for a year is set to units_net based on the status_q_year
