### ISSUE TITLE
Exclude records from Housing Database

### ISSUE THREAD

**Issue by AmandaEyer** [NYCPlanning/db-housing#46]
Where occ_init AND occ_prop IS "Garage/Miscellaneous", do not include in Housing Database output

**Comment by AmandaEyer** [comment]
To exclude new hotel construction from the housing database
Where job_type= NB AND occ_prop = Hotel or Dormitory AND x_mixeduse=[blank] OR in dcp_attributes input no residential unit count (units_prop_res=[blank]), then reclassify record as dcp_occ_category=Other

**Comment by AmandaDoyle** [comment]
@AmandaEyer I corrected the first issue.
I do not understand the details of the second issue.  Can you please answer the following
1) Do you want to exclude records from the housing database Where job_type= NB AND occ_prop = Hotel or Dormitory AND x_mixeduse=[blank]?
2) Can you better explain this part and break down each piece of the logic?
in dcp_attributes input no residential unit count (units_prop_res=[blank]), then reclassify record as dcp_occ_category=Other

**Comment by AmandaEyer** [comment]
I am reconsidering. Yes to 1., and you can just skip 2.
Does that make sense?

**Comment by AmandaDoyle** [comment]
Yep
I implemented the following to export.sql
`job_number NOT IN (
		SELECT DISTINCT job_number 
		FROM housing
		WHERE dob_type = 'NB' AND occ_prop = 'Hotel or Dormitory' AND x_mixeduse IS NULL)`
to exclude new hotel construction from the housing database
