### ISSUE TITLE
Lat Long Mixup

### ISSUE THREAD

**Issue by AmandaEyer** [NYCPlanning/db-housing#50]
Amanda,

These are the jobs that for some reason have switched Lat/Longs. I am not sure if it's a problem with dcp_attributes - I thought I fixed the remaining mistakes yesterday.

[Jobs_LatLong_Switch.txt](https://github.com/NYCPlanning/db-housing/files/2516009/Jobs_LatLong_Switch.txt)

**Comment by AmandaDoyle** [comment]
changed dcpgeoms.sql so that the points will map to the center of the lot by letting it overwrite existing geometries
