### ISSUE TITLE
CO calculation for A1 jobs

### ISSUE THREAD

**Issue by AmandaEyer** [NYCPlanning/db-housing#54]
Please don't calculate (or don't include in the output) any of the year over year unit_change fields based on CO data where job_type=Alteration AND u_init=u_prop.

In doing so, it's important to include any dcp corrected attributes before determining if u_init=u_prop. Your code may already be set up this way, I just want to make sure.

**Comment by AmandaDoyle** [comment]
@AmandaEyer After DCP Edits are applied the unit_change_year fields are calculated in cofosincrem.sql
Confirming:
Are you saying that the unit_change_year fields should not be calculated for A1s where u_init=u_prop?

**Comment by AmandaEyer** [comment]
yes exactly. If an alteration has no change in units, we aren't interested in the CO data. I realized that those alterations do often come with CO data and it makes it all quite messy.

**Comment by AmandaDoyle** [comment]
Added clause to cofosincrem.sql
`WHERE job_number NOT IN
		(SELECT DISTINCT job_number FROM housing
			WHERE dob_type = 'A1' AND units_init=units_prop)`
