### ISSUE TITLE
Units_net should only be calculated when both u_init and u_prop are available

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/db-housing#7]
If u_prop is provided and a CO has been issued, then u_net_incomplete can be calculated

**Comment by AmandaDoyle** [comment]
Added `WHERE units_init ~ '[0-9]' AND units_prop ~ '^[0-9\.]+$'` clause to unitsnet.sql

`WHEN units_net IS NULL AND units_prop IS NOT NULL AND latest_cofo IS NOT NULL THEN (units_prop::numeric - latest_cofo::numeric)::text` in unitsnetcomplete.sql addresses the second issue
